version: "3"
services:
  mysqlservice:
    image: mysql:8
    ports:
      - "3307:3307"
    container_name: mysql-container
    networks:
      - renthub-stackroute-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: root


  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    networks:
      - renthub-stackroute-net
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq-container
    networks:
      - renthub-stackroute-net
    ports:
      - "15672:15672"
      - "5672:5672"



  authenticationservice:
    container_name:  authentication-service
    build: ./
    networks:
      - renthub-stackroute-net
    ports:
      - "8081:8081"
    depends_on:
      - mysqlservice
    restart: always


  apigateway:
    container_name: api-gateway
    build: ./
    networks:
      - renthub-stackroute-net
    ports:
      - "9999:9999"
    restart: always


  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761


  userservice:
    container_name: user-service
    build: ./
    networks:
      - renthub-stackroute-net

    ports:
      - "8065:8065"
    restart: always


  blogservice:
    container_name: blog-service
    build: ./
    networks:
      - renthub-stackroute-net

    ports:
      - "8083:8083"
    restart: always

  chatservice:
    container_name: chat-service
    build: ./
    networks:
      -  renthub-stackroute-net

    ports:
      - "8080:8080"
    restart: always


  emailservice:
    container_name: email-service
    build: ./
    networks:
      -  renthub-stackroute-net

    ports:
      - "8085:8085"
    restart: always


  paymentservice:
    container_name: payment-service
    build: ./
    networks:
      - renthub-stackroute-net

    ports:
      - "8070:8070"
    restart: always


  productservice:
    container_name: product-service
    build: ./
    networks:
      - renthub-stackroute-net

    ports:
      - "8082:8082"
    restart: always

  producthistory:
    container_name: product-history-service
    build: ./
    networks:
      - renthub-stackroute-net

    ports:
      - "8060:8060"
    restart: always

  recommendationservice:
    container_name: recommendation-service
    build: ./
    networks:
      - renthub-stackroute-net

    ports:
      - "8040:8040"
    restart: always

  reviewservice:
    container_name: review-service
    build: ./
    networks:
      - renthub-stackroute-net

    ports:
      - "8050:8050"
    restart: always

  productwebappservice:
    container_name: product-webapp-service
    build: ./
    networks:
      - renthub-stackroute-net

    ports:
      - "8055:8055"
    restart: always


  configurationserver:
    container_name: configuration-server
    build: ./
    networks:
      - renthub-stackroute-net

    ports:
      - "8084-8084"
    restart: always